### ISSUE TITLE
Dataset Download

### ISSUE THREAD

**Issue by zhangquanchen** [jadie1/Point2SSM#1]
Excuse me, how can I download dataset from https://www.shapeworks-cloud.org/#/ . I have not used Shapeworks before. And it looks like a workshop, where I could not find a button or link to download the shape. I can only select it and view the shape.

**Comment by jadie1** [comment]
Hi I apologize, you are correct there is not currently a way to download the data through the web interface. I have added a Python script [download.py](https://github.com/jadie1/Point2SSM/blob/main/download.py) for downloading the data. If you have made an account on [https://www.shapeworks-cloud.org/#/](https://www.shapeworks-cloud.org/#/) then you will be able to run [download.py](https://github.com/jadie1/Point2SSM/blob/main/download.py)  to get the data.

**Comment by zhangquanchen** [comment]
ok, I get it. Thanks so much!
