### ISSUE TITLE
Scripts for calculating generalization and specificity

### ISSUE THREAD

**Issue by zhangquanchen** [jadie1/Point2SSM#3]
Hi, I want to reproduce the results of generalization(Gen.) and specificity(Spec.) for SSM, but I could not find the relevant scripts, just for calculating chamfer distance between shapes is provided. Would you mind further providing the detailed scripts for generalization(Gen.) and specificity(Spec.)? Thank you !

**Comment by jadie1** [comment]
I have not included these scripts as my implementation has many extraneous dependencies. For implementation, you can reference the equations in Appendix C, this [paper](https://pubmed.ncbi.nlm.nih.gov/18787249/), and the [ShapeWorks](https://sciinstitute.github.io/ShapeWorks/latest/) implementation (for [example](https://sciinstitute.github.io/ShapeWorks/latest/use-cases/stats-based/ellipsoid-evaluate.html)).

**Comment by zhangquanchen** [comment]
OK, fine, Thank you for your suggestion.

**Comment by zhangquanchen** [comment]
已收到您的信件！
