### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by zhangquanchen** [jadie1/Point2SSM#4]
I follow the script download.py to download the Pancreas dataset, but I do not exactly know **how you split the dataset to training/testing.**  Besides, would you mind further providing the dataset of **Left Atrium** which you experiment in your paper.

**Comment by jadie1** [comment]
The split was done randomly: 80% train, 10% val, 10% test. I have added the exact split used here: [data/pancreas/](https://github.com/jadie1/Point2SSM/tree/main/data/pancreas). Regarding the left atrium dataset, sadly, it is an in-house dataset at the University of Utah that I cannot publicly share.

**Comment by zhangquanchen** [comment]
I got it! Thank you so much!!!
